evaluation1/urls.py
from django.contrib import admin
from django.contrib.sites.models import Site
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('printers/', include('printers.urls')),
    path('', include('market.urls')),
    path('users/', include('users.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from . import views
from .views import ShoppingCartView, ArticleDetailView, SaleView, SalesView
urlpatterns = [
    path('', views.index, name='home'),
    path('whoweare', views.whoweare, name='whoweare'),
    path('product_detail/<int:pk>', ArticleDetailView.as_view(), name='product_detail'),
    path('shopping_cart/', ShoppingCartView.as_view(), name='shopping_cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('remove_cart_product/<int:cart_id>', views.remove_cart_product, name='remove_cart_product'),
    path('sale/<str:invoice_id>', SaleView.as_view(), name='sale'),
    path('buy', SaleView.as_view(), name='buy'),
    path('sales', SalesView.as_view(), name='sales'),
]

users/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from .views import SessionView, RegistrationView, ProfileView
from . import views


urlpatterns = [
   path('accounts/', include('django.contrib.auth.urls')),
   path('sign_in', SessionView.as_view(), name = "sign_in"),
   path('sign_out', views.sign_out, name = "sign_out"),
   path('sign_up', RegistrationView.as_view(), name= "sign_up"),
   path('profile',ProfileView.as_view(), name = "profile"),
   path('', views.index, name='users'),
   path('new/', views.new, name='new_user'),
   path('<str:user_id>/edit/', views.edit, name='edit_user'),
   path('create', views.create, name='create_user'),
   path('<int:user_id>/', views.show, name='show_user'),
   path('<int:user_id>/update/', views.update, name='update_user'),
   path('<int:user_id>/destroy/', views.destroy, name='destroy_user'),
]  

market/models.py
from django.db import models

# Create your models here.

printers/models.py
from django.db import models
from django.db.models import Sum
from users.models import User
from django.db import transaction
from django.core.exceptions import ValidationError
import random

# Create your models here.
class Printer(models.Model):
    BRANDS = [['hp', 'HP'], ['brother', 'Brother'],['cannon', 'Cannon'], ['lg', 'LG'], ['samsung', 'Samsung']]
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    serial_number = models.TextField()
    brand = models.CharField(max_length=20, choices=BRANDS)
    is_wifi = models.BooleanField(default=False)
    price = models.IntegerField()
    stock = models.IntegerField()
    created_at = models.DateTimeField()
    image = models.ImageField(default=None, null=True, upload_to='printer_images')

    def __str__(self):
        return 'Impresora: %s, Description: %s, Serial: %s, Brand: %s, is_wifi: %s, Price: %s, Stock: %s, Created: %s'%(
            self.name, self.description, self.serial_number, self.brand, self.is_wifi, self.price, self.stock, self.created_at)

class ShoppingCart(models.Model):

    @staticmethod
    def product_quantities(user_id, printer_id):
        return ShoppingCart.objects.filter(
            user_id=user_id, printer_id=printer_id
        ).aggregate(quantities=Sum('quantity'))

    id = models.IntegerField(primary_key=True)
    quantity = models.IntegerField()
    enabled = models.BooleanField(default=True)
    printer = models.ForeignKey(
        Printer,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )   

    def total_price(self):
        return self.quantity * self.printer.price

    
class Sale(models.Model):
    id = models.IntegerField(primary_key=True)
    invoice = models.TextField(unique=True)
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        related_name='sold_items',
    )
    shopping_carts = models.ManyToManyField(ShoppingCart)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

market/views.py
from django.shortcuts import redirect, render
from django.views import View
from printers.models import Printer, Sale, ShoppingCart
from users.models import User
from django.contrib.sessions.backends.db import SessionStore as DBStore
from django.contrib.sessions.base_session import AbstractBaseSession
from django.db import models
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from users.session import SessionStore
import random


def gen_random_hex_string():
    return ''.join(random.choices('0123456789abcdef', k=10))

# Create your views here.   
def index(req):
    user = None
    if req.session.get('_auth_user_id'):
        user = User.objects.get(pk=req.session.get('_auth_user_id'))
    printers = Printer.objects.all()
    context= {'printers': printers, 'user': user}
    return render(req, 'home.html', context)

def whoweare(req):
    user = None
    if req.session.get('_auth_user_id'):
        user = User.objects.get(pk=req.session.get('_auth_user_id'))
    context = {'user': user}
    return render(req, 'whoweare.html', context)

def add_to_cart(req):
    user = None
    if req.session.get('_auth_user_id'):
        user = User.objects.get(pk=req.session.get('_auth_user_id'))
    else:
        return redirect('sign_in')
    quantity = req.GET.get('quantity')
    product_id = req.GET.get('product_id')
    shopping_cart = ShoppingCart(printer_id=product_id, user_id=user.id, quantity=quantity)
    shopping_cart.save()
    return redirect('shopping_cart')

def remove_cart_product(req, cart_id):
    user = None
    if req.session.get('_auth_user_id'):
        user = User.objects.get(pk=req.session.get('_auth_user_id'))
    shopping_cart = ShoppingCart.objects.get(pk=cart_id)
    shopping_cart.delete()
    return redirect('shopping_cart')

class SaleView(View):
    def get(self, request):
        user = None
        if request.session.get('_auth_user_id'):
            user = User.objects.get(pk=request.session.get('_auth_user_id'))
        else:
            return redirect('sign_in')

        invoice_id = request.GET.get('invoice_id')
        sales = Sale.objects.filter(invoice=invoice_id)
        context = {'sales': sales, 'user': user}
        return render(request,'sale.html', context)


    def post(self, request):
        user = None
        if request.session.get('_auth_user_id'):
            user = User.objects.get(pk=request.session.get('_auth_user_id'))
        else:
            return redirect('sign_in')
        shopping_cart_ids = request.POST.getlist('shopping_cart_ids')
        print(shopping_cart_ids)
        shopping_carts = ShoppingCart.objects.filter(id__in=shopping_cart_ids)
        invoice = gen_random_hex_string()
        for cart in shopping_carts:
            printer = Printer.objects.get(id=cart.printer.id)
            print(printer.name)
            printer.stock = printer.stock - cart.quantity
            printer.save()
            cart.enabled = False
            cart.save()
            s = Sale(invoice=invoice, user=user)
            s.save()
            s.shopping_carts.add(cart)

        sales = Sale.objects.filter(invoice=invoice)
        context = {'sales': sales, 'user': user}
        return render(request,'sale.html', context)



class ArticleDetailView(DetailView):

    model = Printer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = None
        if self.request.session.get('_auth_user_id'):
            user = User.objects.get(pk=self.request.session.get('_auth_user_id'))

        context['user'] = user
        return context


class ShoppingCartView(TemplateView):
    template_name ='shopping_cart.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = None
        if self.request.session.get('_auth_user_id'):
            user = User.objects.get(pk=self.request.session.get('_auth_user_id'))
        else:
            context['user'] = user
            return context
        total = 0
        shopping_carts = ShoppingCart.objects.filter(user_id=user.id, enabled=True)
        for cart in shopping_carts:
            total += cart.printer.price * cart.quantity

        context['total'] = total
        context['user'] = user
        context['shopping_carts'] = shopping_carts
        return context

class SalesView(TemplateView):
    template_name ='sales.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = None
        if self.request.session.get('_auth_user_id'):
            user = User.objects.get(pk=self.request.session.get('_auth_user_id'))
        else:
            context['user'] = user
            return context
        total = 0
        sales = Sale.objects.filter(user=user).distinct()
        context['sales'] = sales
        context['user'] = user
        return context

market/templates/base.html
<!DOCTYPE html />
<html lang="es">
  <head>
    <title>Impresoras</title>
    <meta description="My printers CRUD " />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome" />
    <meta name="description" content="página de impresoras" />
    <meta name="keywords" content="printers" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"/>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Inicio</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'whoweare' %}">¿Quiénes somos?</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Mis Productos</a>
            </li>
            {% if user.is_admin %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   href="#"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">
                  Administración
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item" href="{% url 'printers' %}">Productos</a>
                  </li>
                  <li>
                    <hr class="dropdown-divider" />
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'users' %}">Usuarios</a>
                  </li>
                </ul>
              </li>
            {% endif %}
            {% if user is not None %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   href="#"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">
                  <i class="fa-solid fa-basket-shopping"></i><span class="badge text-bg-success">{{ user.shoppingcart_set.all|length }}</span>
                </a>
                <ul class="dropdown-menu">
                  {% for cart in user.shoppingcart_set.all %}
                    <li>
                      <a class="dropdown-item" href="#">{{ cart.printer.name }}</a>
                    </li>
                  {% endfor %}
                  <li>
                    <hr class="dropdown-divider" />
                  </li>
                  <li class="text-center">
                    <a class="btn btn-primary" href="{% url 'shopping_cart' %}">Ir al carro</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   href="#"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">
                  {{ user.name }}
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item" href="{% url 'profile' %}">Perfil</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'sales' %}">Mis compras</a>
                  </li>
                  <li>
                    <hr class="dropdown-divider" />
                  </li>
                  <li class="text-center">
                    <a class="btn btn-danger" href="{% url 'sign_out' %}"><i class="fa fa-user"></i>Cerrar Sesion</a>
                  </li>
                </ul>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sign_in' %}">Iniciar Sesión</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
    <br />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

market/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3">
            {% for printer in printers %}
            <div class="col mb-3">
                    <div class="card h-100 w-100 text-bg-light" style="width: 18rem;">
                        <div class="card-header">
                            {{ printer.name }}
                        </div>
                        {% if printer.image %}
                        <img src="{{ printer.image.url }}" class="card-img-top" alt="Imagen producto">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ printer.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ printer.brand }}</h6>
                            <p class="card-text">{{ printer.description }}</p>
                        </div>
                        <div class="card-footer">
                            <p class="fw-semibold">Stock: {{ printer.stock }}</p>
                            <p class="fw-semibold">Precio: {{ printer.price }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="{% url 'product_detail' printer.id %}" class="btn btn-success">Ver producto </a>
                        </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

market/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row row-cols-3">
            {% for printer in printers %}
            <div class="col h-100">
                    <div class="card" style="width: 18rem;">
                        {% if printer.image %}
                        <img src="{{ printer.image.url }}" class="card-img-top" alt="Imagen producto">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ printer.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ printer.brand }}</h6>
                            <p class="card-text">{{ printer.description }}</p>
                        </div>
                        <div class="card-footer">
                            <p class="fw-semibold">Stock: {{ printer.stock }}</p>
                            <p class="fw-semibold">Precio: {{ printer.price }}</p>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'product_detail' printer.id %}" class="btn btn-success">Ver producto </a>
                        </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

market/templates/sale.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Productos comprados</h1>
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Producto</th>
                                <th>Descripción</th>
                                <th>Cantidad</th>
                                <th>Total</th>
                                <th>Factura</th>
                                <th>Fecha de compra</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for sale in sales %}
                            <tr>
                                <td>
                                    {{ sale.shopping_cart.printer.name }}
                                </td>
                                <td>
                                    {{ sale.shopping_cart.printer.description }}
                                </td>
                                <td>
                                    {{ sale.shopping_cart.quantity }}
                                </td>
                                <td>
                                    {{ sale.shopping_cart.total_price }}
                                </td>
                                <td>{{ sale.invoice }}</td>
                                <td>{{ sale.created_at }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <a href="{% url 'home' %}" class="btn btn-primary mx-auto d-block">Ir a mis compras</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

market/templates/sales.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Productos comprados</h1>
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Fecha Compra</th>
                                <th>Total</th>
                                <th>Factura</th>
                                <th>Fecha de compra</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for sale in sales %}
                            <tr>
                                <td>
                                    {{ sale.id }}
                                </td>
                                <td>
                                    {{ sale.shopping_cart.printer.name }}
                                </td>
                                <td>
                                    {{ sale.shopping_cart.printer.description }}
                                </td>
                                <td>
                                    {{ sale.shopping_cart.quantity }}
                                </td>
                                <td>
                                    {{ sale.shopping_cart.total_price }}
                                </td>
                                <td>{{ sale.invoice }}</td>
                                <td>{{ sale.created_at }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <a href="{% url 'home' %}" class="btn btn-primary mx-auto d-block">Ir a mis compras</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

market/templates/shopping_cart.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>Mis carrito de compras</h1>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Producto</th>
                                    <th>Descripción</th>
                                    <th>Cantidad</th>
                                    <th>Precio</th>
                                    <th>Sub Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cart in shopping_carts %}
                                    <tr>
                                        <td>{{ cart.printer.name }}</td>
                                        <td>{{ cart.printer.description }}</td>
                                        <td>
                                            <i class="fa fa-circle-minus"></i>
                                            <label class="px-2">{{ cart.quantity }}</label>
                                            <i class="fa fa-circle-plus"></i>
                                        </td>
                                        <td>{{ cart.printer.price }}</td>
                                        <td>{{ cart.total_price }}</td>
                                        <td>
                                            <a href="{% url 'remove_cart_product' cart.id %}"><i class="fa-solid fa-trash-can"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>Total :</td>
                                    <td>{{ total }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <form action="{% url 'buy' %}" method="post">
                            {% csrf_token %}
                            {% for cart in shopping_carts %}
                                <input type="hidden" name="shopping_cart_ids" value="{{ cart.id }}" />
                            {% endfor %}
                            <input type="submit"
                                   class="btn btn-success mx-auto d-block"
                                   value="Ir a pagar">
                        </form>
                        <br />
                        <a href="{% url 'home' %}" class="btn btn-primary mx-auto d-block">Seguir comprando</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

market/templates/whoweare.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row row-cols-3">
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="..." class="card-img-top" alt="Imagen Alumno">
                    <div class="card-body">
                        <h5 class="card-title">Erick Kunz</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Analista Programdor</h6>
                        <p class="card-text">Alumnno de INACAP</p>
                    </div>
                    <div class="card-footer">
                        <p class="fw-lighter">Programción Backend</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="..." class="card-img-top" alt="Imagen Alumno">
                    <div class="card-body">
                        <h5 class="card-title">Diego Aguilef</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Analista Programdor</h6>
                        <p class="card-text">Alumnno de INACAP</p>
                    </div>
                    <div class="card-footer">
                        <p class="fw-lighter">Programción Backend</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}